name: Quarto Book Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"

      - name: Install R dependencies
        run: |
          install.packages("renv")
          renv::consent(provided = TRUE)
          renv::restore()
        shell: Rscript {0}

      - name: Render Quarto book
        run: |
          quarto render